---
apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name:
  region:

nodeGroups:
  - name:
    instanceType: m5.large
    minSize: 2
    volumeSize: 50
    volumeType: gp2
    maxSize: 3
    allowSSH: true
    ami: auto
    labels:
      nodegroup-type:
    preBootstrapCommand:
          # allow docker registries to be deployed as cluster service
          - 'echo "{\"bridge\":\"none\",\"log-driver\":\"json-file\",\"log-opts\":{\"max-size\":\"10m\",\"max-file\":\"10\"},\"live-restore\":true,\"max-concurrent-downloads\":10,\"insecure-registries\":[\"172.20.0.0\/16\",\"10.100.0.0\/16\"]}" > /etc/docker/daemon.json'
          - "systemctl restart docker"

availabilityZones: []